# version: "3.7"
services:
  frontend:
    build: hypertube-frontend/
    image: frontend
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./hypertube-frontend/:/app
    depends_on:
      - backend
    environment:
      APP_NAME: 'hypertube'
      ROUTING: true
      # - STYLE=css
    networks:
      - docker-network
    restart: always
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - docker-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  backend:
    build: core-api/
    image: backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      NODE_ENV: development
    volumes:
      - shared-data:/torrents
    networks:
      - docker-network
    depends_on:
      - postgres
  torrent-downloader:
    build: torrent-downloader/
    container_name: torrent-downloader
    ports:
      - "5001:5001"
    volumes:
      - shared-data:/torrents
    networks:
      - docker-network
  torrent-hls-transcoder:
    build: torrent-hls-transcoder/
    container_name: torrent-hls-transcoder
    ports:
      - "5002:5002"
    volumes:
      - shared-data:/torrents
    networks:
      - docker-network
  torrent-scraping:
    build: torrent-scraping/
    container_name: torrent-scraping
    ports:
      - "3001:3001"
    networks:
      - docker-network
  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - libretranslate_data:/home/libretranslate/.local
    networks:
      - docker-network

volumes:
  postgres_data:
  shared-data:
  libretranslate_data:
networks:
  docker-network:
